### PR TITLE
Removing 3.0.0 compatibility.

### LINKED ISSUE #9: Remove backward-compatible imports when 4.0.0 released
Remove the `try`-`import` code that supports older versions of `displayio` et al when 4.0.0 is released as stable.

### PR DESCRIPTION
**Pull request by kattni**
Fixes #9 

Requires testing of bdf.py file.

### CODE REVIEW

**Review by FoamyGuy — COMMENTED** [review]
I get this error: 
```
Traceback (most recent call last):
  File "code.py", line 10, in <module>
  File "/lib/adafruit_bitmap_font/bitmap_font.py", line 56, in load_font
  File "/lib/adafruit_bitmap_font/bdf.py", line 43, in <module>
ImportError: cannot import name Glyph
```
Running on PyPortal with 5.0.0 and 5.1.0.rc0. 

I will test a few other devices.

**Comment by FoamyGuy** [comment]
Same results with EdgeBadge and CPB+Gizmo 5.0.0 on both. Can recreate with REPL:
```
Adafruit CircuitPython 5.0.0 on 2020-03-02; Adafruit Circuit Playground Bluefruit with nRF52840
>>> from displayio import Glyph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Glyph
```

**Comment by kattni** [comment]
@FoamyGuy I may have done this wrong then. I'll take a look tomorrow.

**Comment by tannewt** [comment]
Glyph moved from displayio to fontio so the reverse should work.

**Comment by FoamyGuy** [comment]
I was not sure how to fix the docs conf on this PR so I've created #21 to resolve it. Let me know if I should do something different. 

Tested this changes successfully with the adafruit_display_text simpletest on PyPortal and PyGamer.

**Comment by kattni** [comment]
Closing in favor of #21

**Pull request closed without merging**
